environment: "debug"
db:
    driver: "mysql"
    connection: "delta_user:delta_user@(db:3306)/delta_dashboard"
log:
    level: "debug"
http:
    host: "0.0.0.0"
    port: "8080"

session:
    driver: "memory"
    secret_key: "secret_key"
    connection: ""
    login_max_age_seconds: 36000
    vault_max_age_seconds: 3600
allow_origins:
    - http://localhost:8090
    - http://127.0.0.1:8090

file_storage_type: 1
